# Generated by Django 2.1.1 on 2018-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space_Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=234)),
                ('quantity', models.CharField(max_length=4)),
                ('charge_id', models.CharField(max_length=234)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
